name: command_wrapper
description: Make it easy to create a Dart wrapper for command line tools.
version: 0.1.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  which: '>=0.1.3 <0.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
